name: GCC C CI 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile C code
      run: |
        gcc mkdir.c -o mkdir 
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
         name: mkdir
         path: "/"
